"""add fundraising_time field to c_project

Revision ID: 2b799a86d358
Revises: 6d1b8e2f3f59
Create Date: 2023-03-22 18:47:49.109803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b799a86d358'
down_revision = '6d1b8e2f3f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('fundraising_time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'fundraising_time')
    # ### end Alembic commands ###
